version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.39
    - 15.0.0
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: next-pwa
    versions:
    - 5.2.3
    - 5.2.5
  - dependency-name: "@babel/core"
    versions:
    - 7.13.15
  - dependency-name: "@storybook/react"
    versions:
    - 6.2.2
    - 6.2.5
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.2.5
  - dependency-name: styled-components
    versions:
    - 5.2.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
